h:
cd h:\zakupki
php -f fileupdatenotifications.php done=1
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/notifications/
php -f fileupdatenotifications.php done=2
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Adygeja_Resp/notifications
php -f fileupdatenotifications.php done=3
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altaj_Resp/notifications
php -f fileupdatenotifications.php done=4
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altajskij_kraj/notifications
php -f fileupdatenotifications.php done=5
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Amurskaja_obl/notifications
php -f fileupdatenotifications.php done=6
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Arkhangelskaja_obl/notifications
php -f fileupdatenotifications.php done=7
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Astrakhanskaja_obl/notifications
php -f fileupdatenotifications.php done=8
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bajkonur_g/notifications
php -f fileupdatenotifications.php done=9
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bashkortostan_Resp/notifications
php -f fileupdatenotifications.php done=10
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Belgorodskaja_obl/notifications
php -f fileupdatenotifications.php done=11
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Brjanskaja_obl/notifications
php -f fileupdatenotifications.php done=12
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Burjatija_Resp/notifications
php -f fileupdatenotifications.php done=13
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chechenskaja_Resp/notifications
php -f fileupdatenotifications.php done=14
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Cheljabinskaja_obl/notifications
php -f fileupdatenotifications.php done=15
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chukotskij_AO/notifications
php -f fileupdatenotifications.php done=16
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chuvashskaja_Resp/notifications
php -f fileupdatenotifications.php done=17
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Dagestan_Resp/notifications
php -f fileupdatenotifications.php done=18
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Evrejskaja_Aobl/notifications
php -f fileupdatenotifications.php done=19
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ingushetija_Resp/notifications
php -f fileupdatenotifications.php done=20
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Irkutskaja_obl/notifications
php -f fileupdatenotifications.php done=21
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ivanovskaja_obl/notifications
php -f fileupdatenotifications.php done=22
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jamalo-Neneckij_AO/notifications
php -f fileupdatenotifications.php done=23
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jaroslavskaja_obl/notifications
php -f fileupdatenotifications.php done=24
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kabardino-Balkarskaja_Resp/notifications
php -f fileupdatenotifications.php done=25
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaliningradskaja_obl/notifications
php -f fileupdatenotifications.php done=26
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kalmykija_Resp/notifications
php -f fileupdatenotifications.php done=27
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaluzhskaja_obl/notifications
php -f fileupdatenotifications.php done=28
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kamchatskij_kraj/notifications
php -f fileupdatenotifications.php done=29
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karachaevo-Cherkesskaja_Resp/notifications
php -f fileupdatenotifications.php done=30
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karelija_Resp/notifications
php -f fileupdatenotifications.php done=31
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kemerovskaja_obl/notifications
php -f fileupdatenotifications.php done=32
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khabarovskij_kraj/notifications
php -f fileupdatenotifications.php done=33
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khakasija_Resp/notifications
php -f fileupdatenotifications.php done=34
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khanty-Mansijskij_AO-Jugra_AO/notifications
php -f fileupdatenotifications.php done=35
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kirovskaja_obl/notifications
php -f fileupdatenotifications.php done=36
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Komi_Resp/notifications
php -f fileupdatenotifications.php done=37
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kostromskaja_obl/notifications
php -f fileupdatenotifications.php done=38
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnodarskij_kraj/notifications
php -f fileupdatenotifications.php done=39
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnojarskij_kraj/notifications
php -f fileupdatenotifications.php done=40
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krim_Resp/notifications
php -f fileupdatenotifications.php done=41
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurganskaja_obl/notifications
php -f fileupdatenotifications.php done=42
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurskaja_obl/notifications
php -f fileupdatenotifications.php done=43
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Leningradskaja_obl/notifications
php -f fileupdatenotifications.php done=44
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Lipeckaja_obl/notifications
php -f fileupdatenotifications.php done=45
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Magadanskaja_obl/notifications
php -f fileupdatenotifications.php done=46
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/notifications
php -f fileupdatenotifications.php done=47
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Mordovija_Resp/notifications
php -f fileupdatenotifications.php done=48
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskovskaja_obl/notifications
php -f fileupdatenotifications.php done=49
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskva/notifications
php -f fileupdatenotifications.php done=50
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Murmanskaja_obl/notifications
php -f fileupdatenotifications.php done=51
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Neneckij_AO/notifications
php -f fileupdatenotifications.php done=52
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Nizhegorodskaja_obl/notifications
php -f fileupdatenotifications.php done=53
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novgorodskaja_obl/notifications
php -f fileupdatenotifications.php done=54
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novosibirskaja_obl/notifications
php -f fileupdatenotifications.php done=55
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Omskaja_obl/notifications
php -f fileupdatenotifications.php done=56
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orenburgskaja_obl/notifications
php -f fileupdatenotifications.php done=57
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orlovskaja_obl/notifications
php -f fileupdatenotifications.php done=58
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/PG-PZ/notifications
php -f fileupdatenotifications.php done=59
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Penzenskaja_obl/notifications
php -f fileupdatenotifications.php done=60
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Permskij_kraj/notifications
php -f fileupdatenotifications.php done=61
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Primorskij_kraj/notifications
php -f fileupdatenotifications.php done=62
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Pskovskaja_obl/notifications
php -f fileupdatenotifications.php done=63
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rjazanskaja_obl/notifications
php -f fileupdatenotifications.php done=64
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rostovskaja_obl/notifications
php -f fileupdatenotifications.php done=65
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakha_Jakutija_Resp/notifications
php -f fileupdatenotifications.php done=66
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakhalinskaja_obl/notifications
php -f fileupdatenotifications.php done=67
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Samarskaja_obl/notifications
php -f fileupdatenotifications.php done=68
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sankt-Peterburg/notifications
php -f fileupdatenotifications.php done=69
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Saratovskaja_obl/notifications
php -f fileupdatenotifications.php done=70
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sevastopol_g/notifications
php -f fileupdatenotifications.php done=71
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Severnaja_Osetija-Alanija_Resp/notifications
php -f fileupdatenotifications.php done=72
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Smolenskaja_obl/notifications
php -f fileupdatenotifications.php done=73
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Stavropolskij_kraj/notifications
php -f fileupdatenotifications.php done=74
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sverdlovskaja_obl/notifications
php -f fileupdatenotifications.php done=75
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tambovskaja_obl/notifications
php -f fileupdatenotifications.php done=76
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tatarstan_Resp/notifications
php -f fileupdatenotifications.php done=77
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tjumenskaja_obl/notifications
php -f fileupdatenotifications.php done=78
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tomskaja_obl/notifications
php -f fileupdatenotifications.php done=79
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tulskaja_obl/notifications
php -f fileupdatenotifications.php done=80
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tverskaja_obl/notifications
php -f fileupdatenotifications.php done=81
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tyva_Resp/notifications
php -f fileupdatenotifications.php done=82
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Udmurtskaja_Resp/notifications
php -f fileupdatenotifications.php done=83
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Uljanovskaja_obl/notifications
php -f fileupdatenotifications.php done=84
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vladimirskaja_obl/notifications
php -f fileupdatenotifications.php done=85
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Volgogradskaja_obl/notifications
php -f fileupdatenotifications.php done=86
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vologodskaja_obl/notifications
php -f fileupdatenotifications.php done=87
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Voronezhskaja_obl/notifications
php -f fileupdatenotifications.php done=88
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Zabajkalskij_kraj/notifications
php -f fileupdatenotifications.php done=100
exit