h:
cd h:\zakupki
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/contracts/
php -f fileupdatecontracts.php done=1
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Adygeja_Resp/contracts
php -f fileupdatecontracts.php done=2
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altaj_Resp/contracts
php -f fileupdatecontracts.php done=3
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Altajskij_kraj/contracts
php -f fileupdatecontracts.php done=4
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Amurskaja_obl/contracts
php -f fileupdatecontracts.php done=5
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Arkhangelskaja_obl/contracts
php -f fileupdatecontracts.php done=6
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Astrakhanskaja_obl/contracts
php -f fileupdatecontracts.php done=7
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bajkonur_g/contracts
php -f fileupdatecontracts.php done=8
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Bashkortostan_Resp/contracts
php -f fileupdatecontracts.php done=9
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Belgorodskaja_obl/contracts
php -f fileupdatecontracts.php done=10
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Brjanskaja_obl/contracts
php -f fileupdatecontracts.php done=11
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Burjatija_Resp/contracts
php -f fileupdatecontracts.php done=12
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chechenskaja_Resp/contracts
php -f fileupdatecontracts.php done=13
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Cheljabinskaja_obl/contracts
php -f fileupdatecontracts.php done=14
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chukotskij_AO/contracts
php -f fileupdatecontracts.php done=15
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Chuvashskaja_Resp/contracts
php -f fileupdatecontracts.php done=16
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Dagestan_Resp/contracts
php -f fileupdatecontracts.php done=17
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Evrejskaja_Aobl/contracts
php -f fileupdatecontracts.php done=18
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ingushetija_Resp/contracts
php -f fileupdatecontracts.php done=19
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Irkutskaja_obl/contracts
php -f fileupdatecontracts.php done=21
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Ivanovskaja_obl/contracts
php -f fileupdatecontracts.php done=22
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jamalo-Neneckij_AO/contracts
php -f fileupdatecontracts.php done=23
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Jaroslavskaja_obl/contracts
php -f fileupdatecontracts.php done=24
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kabardino-Balkarskaja_Resp/contracts
php -f fileupdatecontracts.php done=25
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaliningradskaja_obl/contracts
php -f fileupdatecontracts.php done=26
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kalmykija_Resp/contracts
php -f fileupdatecontracts.php done=27
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kaluzhskaja_obl/contracts
php -f fileupdatecontracts.php done=28
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kamchatskij_kraj/contracts
php -f fileupdatecontracts.php done=29
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karachaevo-Cherkesskaja_Resp/contracts
php -f fileupdatecontracts.php done=30
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Karelija_Resp/contracts
php -f fileupdatecontracts.php done=31
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kemerovskaja_obl/contracts
php -f fileupdatecontracts.php done=32
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khabarovskij_kraj/contracts
php -f fileupdatecontracts.php done=34
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khakasija_Resp/contracts
php -f fileupdatecontracts.php done=35
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Khanty-Mansijskij_AO-Jugra_AO/contracts
php -f fileupdatecontracts.php done=36
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kirovskaja_obl/contracts
php -f fileupdatecontracts.php done=37
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Komi_Resp/contracts
php -f fileupdatecontracts.php done=38
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kostromskaja_obl/contracts
php -f fileupdatecontracts.php done=39
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnodarskij_kraj/contracts
php -f fileupdatecontracts.php done=42
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krasnojarskij_kraj/contracts
php -f fileupdatecontracts.php done=43
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Krim_Resp/contracts
php -f fileupdatecontracts.php done=44
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurganskaja_obl/contracts
php -f fileupdatecontracts.php done=45
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Kurskaja_obl/contracts
php -f fileupdatecontracts.php done=46
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Leningradskaja_obl/contracts
php -f fileupdatecontracts.php done=49
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Lipeckaja_obl/contracts
php -f fileupdatecontracts.php done=50
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Magadanskaja_obl/contracts
php -f fileupdatecontracts.php done=51
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Marij_El_Resp/contracts
php -f fileupdatecontracts.php done=52
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Mordovija_Resp/contracts
php -f fileupdatecontracts.php done=53
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskovskaja_obl/contracts
php -f fileupdatecontracts.php done=56
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Moskva/contracts
php -f fileupdatecontracts.php done=60
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Murmanskaja_obl/contracts
php -f fileupdatecontracts.php done=61
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Neneckij_AO/contracts
php -f fileupdatecontracts.php done=62
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Nizhegorodskaja_obl/contracts
php -f fileupdatecontracts.php done=64
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novgorodskaja_obl/contracts
php -f fileupdatecontracts.php done=65
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Novosibirskaja_obl/contracts
php -f fileupdatecontracts.php done=67
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Omskaja_obl/contracts
php -f fileupdatecontracts.php done=68
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orenburgskaja_obl/contracts
php -f fileupdatecontracts.php done=69
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Orlovskaja_obl/contracts
php -f fileupdatecontracts.php done=70
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/PG-PZ/contracts
php -f fileupdatecontracts.php done=71
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Penzenskaja_obl/contracts
php -f fileupdatecontracts.php done=72
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Permskij_kraj/contracts
php -f fileupdatecontracts.php done=73
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Primorskij_kraj/contracts
php -f fileupdatecontracts.php done=74
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Pskovskaja_obl/contracts
php -f fileupdatecontracts.php done=75
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rjazanskaja_obl/contracts
php -f fileupdatecontracts.php done=76
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Rostovskaja_obl/contracts
php -f fileupdatecontracts.php done=77
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakha_Jakutija_Resp/contracts
php -f fileupdatecontracts.php done=78
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sakhalinskaja_obl/contracts
php -f fileupdatecontracts.php done=79
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Samarskaja_obl/contracts
php -f fileupdatecontracts.php done=80
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sankt-Peterburg/contracts
php -f fileupdatecontracts.php done=83
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Saratovskaja_obl/contracts
php -f fileupdatecontracts.php done=84
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sevastopol_g/contracts
php -f fileupdatecontracts.php done=85
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Severnaja_Osetija-Alanija_Resp/contracts
php -f fileupdatecontracts.php done=86
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Smolenskaja_obl/contracts
php -f fileupdatecontracts.php done=87
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Stavropolskij_kraj/contracts
php -f fileupdatecontracts.php done=88
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Sverdlovskaja_obl/contracts
php -f fileupdatecontracts.php done=89
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tambovskaja_obl/contracts
php -f fileupdatecontracts.php done=90
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tatarstan_Resp/contracts
php -f fileupdatecontracts.php done=91
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tjumenskaja_obl/contracts
php -f fileupdatecontracts.php done=92
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tomskaja_obl/contracts
php -f fileupdatecontracts.php done=93
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tulskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tverskaja_obl/contracts
php -f fileupdatecontracts.php done=94
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Tyva_Resp/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Udmurtskaja_Resp/contracts
php -f fileupdatecontracts.php done=95
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Uljanovskaja_obl/contracts
php -f fileupdatecontracts.php done=96
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vladimirskaja_obl/contracts
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Volgogradskaja_obl/contracts
php -f fileupdatecontracts.php done=97
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Vologodskaja_obl/contracts
php -f fileupdatecontracts.php done=98
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Voronezhskaja_obl/contracts
php -f fileupdatecontracts.php done=99
wget -r -nc ftp://free:free@ftp.zakupki.gov.ru/fcs_regions/Zabajkalskij_kraj/contracts
php -f fileupdatecontracts.php done=100
exit